### PR TITLE
Use CMake to build libevent

### PR DESCRIPTION
**Pull request by uilianries**
Hi!

Since libevent offers CMake support, I think we could move the recipe to use it.

### CODE REVIEW

**Review by theirix — COMMENTED** [review]
Hello! Thank you for the PR, it could be a great simplification of the libevent build. I tried to do it before but, unfortunately, libevent does not officially support CMake build:

1. [Readme](https://github.com/libevent/libevent/blob/release-2.1.8-stable/README.md) clearly states that CMake support is experimental:
> (Note that autoconf is currently the most mature and supported build enviroment for libevent; the cmake instructions here are new and experimental, though they should be solid. We hope that cmake will still be supported in future versions of Libevent, and will try to make sure that happens.)

2. libevent even missing CMakeLists.txt from the official signed 2.1.8 release (see bugs 502, 551). Please note that GitHub provides for 2.1.8 both official tarball (without cmake) and tarballs with repository content (with cmake). For packaging, I prefer to use only official archives, not the auto-generated GitHub archives.

It will be good if cmake was supported officially but it isn't yet. Let's wait for 2.2 at least.

**Comment by uilianries** [comment]
Hi @theirix thanks for the clarification. I'll close this PR, we can re-use it for 2.2

**Comment by theirix** [comment]
@uilianries great! I am tracking those libevent+cmake tickets and releases so we can package it soon enough.

**Comment by Croydon** [comment]
I have created https://github.com/bincrafters/conan-libevent/tree/cmake/2.1.8 to keep the changes around, but I'm going to remove them from `testing/` for now

**Comment by uilianries** [comment]
Thanks @Croydon

**Pull request closed without merging**
